services:
  mysql:
    image: mysql:latest
    container_name: inventry-service-mysql
    ports:
      - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql